package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "radio_hal",
    hdrs = ["radio_hal.h"],
)

cc_library(
    name = "radio_spidev",
    hdrs = ["radio_spidev.h"],
)
